title: Juan Torres
description: Business Administration and Logistics Management at Central Michigan University. Operations experience, and projects in routing, simulation and supply chain.
baseurl: ""
url: "https://juantorresmi.github.io"
theme: null
markdown: kramdown
permalink: pretty
