title: Juan Torres
description: Certified Meat Cutter | Logistics & Supply Chain Management
baseurl: ""
url: "https://JuanTorres.xyz"
theme: null
markdown: kramdown
permalink: pretty
markdown: kramdown